name: pulldigest
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - PyGithub
    - requests
    - tree-sitter
    - tiktoken
    - scikit-learn
    - lightgbm
    - pandas
    - huggingface-hub
    - gitpython
    - mkdocs
